### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by T0biasCZe** [mofosyne/arduino-gameboy-printer-emulator#58]
The program always throws error "// Timed Out (Memory Waterline: 6B out of 650B)" while printing (and error #02 on screen)
Sometimes it does it after transfer
![obrazek](https://user-images.githubusercontent.com/44525446/142044744-a3cb429c-d55c-45e1-a3af-09712c64dee2.png)

But sometimes the "print" screen flashes for half second and then it throws that error...
also once it threw it twice, one time mid transfer, and then after transfer finished

**Comment by T0biasCZe** [comment]
example of console output when the printing screen flashes
![obrazek](https://user-images.githubusercontent.com/44525446/142050366-0daa6a2c-00bb-4386-bd72-4400666faa40.png)

(even though the timeout, the hex always works)

**Comment by mofosyne** [comment]
Investigated. I can see that somewhere we dropped checks on the status byte when doing simulated printing for raw packet capture.

It's unlikely to cause any problem so I've just changed the message to "completed" rather than "timeout" which is more accurate anyway for https://github.com/mofosyne/arduino-gameboy-printer-emulator/releases/tag/v3.2.1

There may be more optimal changes, but to avoid breaking any other games that we worked hard to support, we opted to just do this small change.

Thanks for reporting this issue. Do let me know if you cannot download any images.
